### ISSUE TITLE
Container for Unimus Core

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus#7]
Hi,

Not specifically related to this repository, but with release of Unimus 2.0.0, there is a new "Unimus Core" distribution, which serves as the remote agent / remote proxy for the new "Zones" feature.

A separate container for Unimus Core (docker-unimus-core) would be much appreciated!

Going forward, links for Core distributions will be:
https://unimus.net/download-unimus-core/-%20Latest/Unimus-Core.jar - latest stable release
https://unimus.net/download-unimus-core/x.x.x/Unimus-Core.jar - history of stable releases
https://unimus.net/download-unimus-core/dev-builds/Unimus-Core.jar - development releases

Development releases for Unimus with Zones support, as well as Unimus Core are already available at https://unimus.net/download-dev.

Since this is new, documentation is still lacking, but will be available here soon:
https://wiki.unimus.net/display/UNPUB/Architecture+overview
https://wiki.unimus.net/display/UNPUB/Zones

**Comment by tomaskir** [comment]
As an additional note, this repository will not be affected in any way.
Unimus will continue to work as before without any modifications.

Starting with 2.0.0, Unimus itself has an embedded Core inside `Unimus.jar`, so for users that don't want to manage remote networks, there are no changes.

As such, simply running Unimus from the current containers will continue working as expected.

**Comment by crocandr** [comment]
Hi,

Thank you for the ticket :)
I've created a new repo for unimus core, as you wish :)
https://github.com/crocandr/docker-unimus-core

I'm going to create some automatic build for the new versions of unimus and unimus core images.

I've created the first version of unimus core but I got this error (docker-compose logs output):
```
...
unimus-core_1  | 2020-04-09 14:59:52.169  WARN 17 --- [o-assembling-10] s.netcore.tcp.client.SpringTcpClient     : Connection deserialization exception caught 'Expected STX to begin message'
unimus-core_1  | 2020-04-09 14:59:52.170  WARN 17 --- [io-processing-2] i.ClientNegotiationConnectionInterceptor : Error message received 'Connection is closed'
unimus-core_1  | 2020-04-09 14:59:57.169  WARN 17 --- [io-assembling-1] s.netcore.tcp.client.SpringTcpClient     : Connection deserialization exception caught 'Expected STX to begin message'
unimus-core_1  | 2020-04-09 14:59:57.169  WARN 17 --- [io-processing-5] i.ClientNegotiationConnectionInterceptor : Error message received 'Connection is closed'
unimus-core_1  | 2020-04-09 15:00:02.170  WARN 17 --- [io-processing-4] i.ClientNegotiationConnectionInterceptor : Error message received 'Connection is closed'
unimus-core_1  | 2020-04-09 15:00:07.171  WARN 17 --- [io-processing-2] i.ClientNegotiationConnectionInterceptor : Error message received 'Connection is closed'
...
```
Is it normal or missed something?

**Comment by tomaskir** [comment]
Apologies - issue on our end. Binaries that were published for Unimus and Unimus Core did not have same communication library versions.

Should hopefully be fixed now - if you pull latest binaries from the dev page, they should work together.

**Comment by crocandr** [comment]
Thank you!

I updated both binaries and built new images on my local test machine.
I started unimus server with an empty database too and I get this error when I try to create a new zone:
(example parameters: zone name: `test`, `zonetest` or `zoneA`, zone id: 2, 111, 9, 999... same error :( ) 

```
...
unimus_1  | 2020-04-09 22:27:02.273 ERROR 8 --- [nio-8085-exec-6] com.vaadin.server.DefaultErrorHandler    :
unimus_1  |
unimus_1  | java.lang.NullPointerException: null
unimus_1  |     at net.unimus.ui.widget.zone.ZoneForm.getModel(ZoneForm.java:121)
unimus_1  |     at net.unimus.ui.widget.zone.AddZonePopup.lambda$showConfirmBtn$61446b05$1(AddZonePopup.java:73)
unimus_1  |     at net.unimus.common.ui.widget.FButton$FocusClearingClickListener.buttonClick(FButton.java:33)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
unimus_1  |     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
unimus_1  |     at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
unimus_1  |     at com.vaadin.ui.Button.fireClick(Button.java:377)
unimus_1  |     at org.vaadin.viritin.button.MButton.fireClick(MButton.java:148)
unimus_1  |     at com.vaadin.ui.Button$1.click(Button.java:54)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
unimus_1  |     at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
unimus_1  |     at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
unimus_1  |     at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:494)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
unimus_1  |     at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
unimus_1  |     at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
unimus_1  |     at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:214)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:211)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
unimus_1  |     at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
unimus_1  |     at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
unimus_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
unimus_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
unimus_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
unimus_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
unimus_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
unimus_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
unimus_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
unimus_1  |     at java.base/java.lang.Thread.run(Thread.java:834)
unimus_1  |

```

I have not seen this error.
Do you have any idea?

**Comment by tomaskir** [comment]
@Leaghte & @Jozef-Petrik could you please look at this?

**Comment by tomaskir** [comment]
First of all thanks again for helping us test this.

We've just pushed a fixed build with multiple fixes for the Zones feature, as well as multiple fixes for Mass Config Push.

If/when you get a time to test, please let me know if everything behaves :)

**Comment by crocandr** [comment]
Thank you very much. 
Sorry, but I've tried lots of things, but the problem is same :(

Downloaded the latest unimus jar file from the dev site manually and with the automatic docker image build too, updated the unimus image many times, but I see this version every time:
```
unimus_1  | :: ? 2016-2020 NetCore j.s.a. :: version 2.0.0-Beta2 ::
```

I've tried with HSQL instead of MySQL too, but I the error is same :(

```
...
unimus_1  | 2020-04-10 23:20:32.863 ERROR 8 --- [nio-8085-exec-3] com.vaadin.server.DefaultErrorHandler    :
unimus_1  |
unimus_1  | java.lang.NullPointerException: null
unimus_1  |     at net.unimus.ui.widget.zone.ZoneForm.getModel(ZoneForm.java:121)
unimus_1  |     at net.unimus.ui.widget.zone.AddZonePopup.lambda$showConfirmBtn$61446b05$1(AddZonePopup.java:73)
unimus_1  |     at net.unimus.common.ui.widget.FButton$FocusClearingClickListener.buttonClick(FButton.java:33)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
unimus_1  |     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
unimus_1  |     at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
unimus_1  |     at com.vaadin.ui.Button.fireClick(Button.java:377)
unimus_1  |     at org.vaadin.viritin.button.MButton.fireClick(MButton.java:148)
unimus_1  |     at com.vaadin.ui.Button$1.click(Button.java:54)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
unimus_1  |     at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
unimus_1  |     at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
unimus_1  |     at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:494)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
unimus_1  |     at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
unimus_1  |     at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
unimus_1  |     at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:214)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:211)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
unimus_1  |     at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
unimus_1  |     at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
unimus_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
unimus_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
unimus_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
unimus_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
unimus_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
unimus_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
unimus_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
unimus_1  |     at java.base/java.lang.Thread.run(Thread.java:834)
unimus_1  |
```

What am I doing wrong?
How can I download the fixed/updated latest binary?

Very sorry for the bad news :(

**Comment by tomaskir** [comment]
We have bumped the version to Beta3 and released another set of updated binaries.
Can you please retest with these? (please check if both Unimus and Core report Beta3 at startup)

Sorry you are running into these issue :(

**Comment by crocandr** [comment]
Something still wrong :(

```
unimus_1  | 2020-04-14 13:31:33.214 ERROR 10 --- [nio-8085-exec-5] com.vaadin.server.DefaultErrorHandler    :
unimus_1  |
unimus_1  | java.lang.NullPointerException: null
unimus_1  |     at net.unimus.ui.widget.zone.ZoneForm.getModel(ZoneForm.java:121)
unimus_1  |     at net.unimus.ui.widget.zone.AddZonePopup.lambda$showConfirmBtn$61446b05$1(AddZonePopup.java:73)
unimus_1  |     at net.unimus.common.ui.widget.FButton$FocusClearingClickListener.buttonClick(FButton.java:33)
unimus_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
unimus_1  |     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
unimus_1  |     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
unimus_1  |     at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
unimus_1  |     at com.vaadin.ui.Button.fireClick(Button.java:377)
unimus_1  |     at org.vaadin.viritin.button.MButton.fireClick(MButton.java:148)
unimus_1  |     at com.vaadin.ui.Button$1.click(Button.java:54)
unimus_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unimus_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unimus_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unimus_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
unimus_1  |     at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
unimus_1  |     at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
unimus_1  |     at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
unimus_1  |     at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
unimus_1  |     at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:494)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
unimus_1  |     at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
unimus_1  |     at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
unimus_1  |     at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
unimus_1  |     at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
unimus_1  |     at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
unimus_1  |     at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:214)
unimus_1  |     at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:211)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
unimus_1  |     at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
unimus_1  |     at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
unimus_1  |     at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
unimus_1  |     at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
unimus_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
unimus_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
unimus_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
unimus_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
unimus_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
unimus_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
unimus_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
unimus_1  |     at java.lang.Thread.run(Thread.java:748)
unimus_1  |
```

I've tried with HSQL, MYSQL java8, and java11 but I got this same error... :(

**Comment by crocandr** [comment]
Sorry, I missed it, my fault :(

The Description field doesn't have a "red star" so I thought is not required.
![image](https://user-images.githubusercontent.com/7159285/79224087-d4c41c80-7e5a-11ea-8cd1-0a520495c1b6.png)

But if I filled this field too, the zone is created without any problem :)

**Comment by crocandr** [comment]
The unimus-core is connected now :)

![image](https://user-images.githubusercontent.com/7159285/79224644-c0ccea80-7e5b-11ea-83bc-67e53c8763fc.png)

Thank you!

**Comment by tomaskir** [comment]
The description field should indeed be optional - the devs are looking into it now :)

**Comment by tomaskir** [comment]
We just released another build (marked as Beta4) that should have the empty description fixed.
Thanks again for testing!

**Comment by crocandr** [comment]
Thank you for the very quick fix and sorry for late

Everything is perfect :)
![image](https://user-images.githubusercontent.com/7159285/79265933-24c0d480-7e97-11ea-8ef2-a1f5d07fba04.png)

I've created the "test2" zone without description and without any problem :)
Thank you!

This unimus image is available on the docker hub with `2.0.0-Beta4` tag.
